create extension if not exists "uuid-ossp";

create table if not exists geo
(
    id                UUID unique          not null default uuid_generate_v1() primary key,
    country_name      varchar(50) unique   not null,
    country_code      varchar(2) unique    not null
);

alter table geo
    owner to postgres;

insert into geo(country_name, country_code) values ('Fiji', 'FJ');
insert into geo(country_name, country_code) values ('Tanzania', 'TZ');
insert into geo(country_name, country_code) values ('Western Sahara', 'EH');
insert into geo(country_name, country_code) values ('Canada', 'CA');
insert into geo(country_name, country_code) values ('United States', 'US');
insert into geo(country_name, country_code) values ('Kazakhstan', 'KZ');
insert into geo(country_name, country_code) values ('Uzbekistan', 'UZ');
insert into geo(country_name, country_code) values ('Papua New Guinea', 'PG');
insert into geo(country_name, country_code) values ('Argentina', 'AR');
insert into geo(country_name, country_code) values ('Chile', 'CL');
insert into geo(country_name, country_code) values ('Democratic Republic of the Congo', 'CD');
insert into geo(country_name, country_code) values ('Somalia', 'SO');
insert into geo(country_name, country_code) values ('Kenya', 'KE');
insert into geo(country_name, country_code) values ('Sudan', 'SD');
insert into geo(country_name, country_code) values ('Chad', 'TD');
insert into geo(country_name, country_code) values ('Haiti', 'HT');
insert into geo(country_name, country_code) values ('Dominican Republic', 'DO');
insert into geo(country_name, country_code) values ('Russia', 'RU');
insert into geo(country_name, country_code) values ('Bahamas', 'BS');
insert into geo(country_name, country_code) values ('Falkland Islands', 'FK');
insert into geo(country_name, country_code) values ('Norway', 'NO');
insert into geo(country_name, country_code) values ('Greenland', 'GL');
insert into geo(country_name, country_code) values ('Timor-Leste', 'TL');
insert into geo(country_name, country_code) values ('South Africa', 'ZA');
insert into geo(country_name, country_code) values ('Lesotho', 'LS');
insert into geo(country_name, country_code) values ('Mexico', 'MX');
insert into geo(country_name, country_code) values ('Uruguay', 'UY');
insert into geo(country_name, country_code) values ('Brazil', 'BR');
insert into geo(country_name, country_code) values ('Bolivia', 'BO');
insert into geo(country_name, country_code) values ('Peru', 'PE');
insert into geo(country_name, country_code) values ('Colombia', 'CO');
insert into geo(country_name, country_code) values ('Panama', 'PA');
insert into geo(country_name, country_code) values ('Costa Rica', 'CR');
insert into geo(country_name, country_code) values ('Nicaragua', 'NI');
insert into geo(country_name, country_code) values ('Honduras', 'HN');
insert into geo(country_name, country_code) values ('El Salvador', 'SV');
insert into geo(country_name, country_code) values ('Guatemala', 'GT');
insert into geo(country_name, country_code) values ('Belize', 'BZ');
insert into geo(country_name, country_code) values ('Venezuela', 'VE');
insert into geo(country_name, country_code) values ('Guyana', 'GY');
insert into geo(country_name, country_code) values ('Suriname', 'SR');
insert into geo(country_name, country_code) values ('France', 'FR');
insert into geo(country_name, country_code) values ('Ecuador', 'EC');
insert into geo(country_name, country_code) values ('Puerto Rico', 'PR');
insert into geo(country_name, country_code) values ('Jamaica', 'JM');
insert into geo(country_name, country_code) values ('Cuba', 'CU');
insert into geo(country_name, country_code) values ('Zimbabwe', 'ZW');
insert into geo(country_name, country_code) values ('Botswana', 'BW');
insert into geo(country_name, country_code) values ('Namibia', 'NA');
insert into geo(country_name, country_code) values ('Senegal', 'SN');
insert into geo(country_name, country_code) values ('Mali', 'ML');
insert into geo(country_name, country_code) values ('Mauritania', 'MR');
insert into geo(country_name, country_code) values ('Benin', 'BJ');
insert into geo(country_name, country_code) values ('Niger', 'NE');
insert into geo(country_name, country_code) values ('Nigeria', 'NG');
insert into geo(country_name, country_code) values ('Cameroon', 'CM');
insert into geo(country_name, country_code) values ('Togo', 'TG');
insert into geo(country_name, country_code) values ('Ghana', 'GH');
insert into geo(country_name, country_code) values ('Côted Ivoire', 'CI');
insert into geo(country_name, country_code) values ('Guinea', 'GN');
insert into geo(country_name, country_code) values ('Guinea-Bissau', 'GW');
insert into geo(country_name, country_code) values ('Liberia', 'LR');
insert into geo(country_name, country_code) values ('Sierra Leone', 'SL');
insert into geo(country_name, country_code) values ('Burkina Faso', 'BF');
insert into geo(country_name, country_code) values ('Central African Republic', 'CF');
insert into geo(country_name, country_code) values ('Republic of the Congo', 'CG');
insert into geo(country_name, country_code) values ('Gabon', 'GA');
insert into geo(country_name, country_code) values ('Equatorial Guinea', 'GQ');
insert into geo(country_name, country_code) values ('Zambia', 'ZM');
insert into geo(country_name, country_code) values ('Malawi', 'MW');
insert into geo(country_name, country_code) values ('Mozambique', 'MZ');
insert into geo(country_name, country_code) values ('Eswatini', 'SZ');
insert into geo(country_name, country_code) values ('Angola', 'AO');
insert into geo(country_name, country_code) values ('Burundi', 'BI');
insert into geo(country_name, country_code) values ('Israel', 'IL');
insert into geo(country_name, country_code) values ('Lebanon', 'LB');
insert into geo(country_name, country_code) values ('Madagascar', 'MG');
insert into geo(country_name, country_code) values ('The Gambia', 'GM');
insert into geo(country_name, country_code) values ('Tunisia', 'TN');
insert into geo(country_name, country_code) values ('Algeria', 'DZ');
insert into geo(country_name, country_code) values ('Jordan', 'JO');
insert into geo(country_name, country_code) values ('United Arab Emirates', 'AE');
insert into geo(country_name, country_code) values ('Qatar', 'QA');
insert into geo(country_name, country_code) values ('Kuwait', 'KW');
insert into geo(country_name, country_code) values ('Iraq', 'IQ');
insert into geo(country_name, country_code) values ('Oman', 'OM');
insert into geo(country_name, country_code) values ('Vanuatu', 'VU');
insert into geo(country_name, country_code) values ('Cambodia', 'KH');
insert into geo(country_name, country_code) values ('Thailand', 'TH');
insert into geo(country_name, country_code) values ('Lao PDR', 'LA');
insert into geo(country_name, country_code) values ('Myanmar', 'MM');
insert into geo(country_name, country_code) values ('Vietnam', 'VN');
insert into geo(country_name, country_code) values ('Dem. Rep. Korea', 'KP');
insert into geo(country_name, country_code) values ('Republic of Korea', 'KR');
insert into geo(country_name, country_code) values ('Mongolia', 'MN');
insert into geo(country_name, country_code) values ('India', 'IN');
insert into geo(country_name, country_code) values ('Bangladesh', 'BD');
insert into geo(country_name, country_code) values ('Bhutan', 'BT');
insert into geo(country_name, country_code) values ('Nepal', 'NP');
insert into geo(country_name, country_code) values ('Pakistan', 'PK');
insert into geo(country_name, country_code) values ('Afghanistan', 'AF');
insert into geo(country_name, country_code) values ('Tajikistan', 'TJ');
insert into geo(country_name, country_code) values ('Kyrgyzstan', 'KG');
insert into geo(country_name, country_code) values ('Turkmenistan', 'TM');
insert into geo(country_name, country_code) values ('Iran', 'IR');
insert into geo(country_name, country_code) values ('Syria', 'SY');
insert into geo(country_name, country_code) values ('Armenia', 'AM');
insert into geo(country_name, country_code) values ('Sweden', 'SE');
insert into geo(country_name, country_code) values ('Belarus', 'BY');
insert into geo(country_name, country_code) values ('Ukraine', 'UA');
insert into geo(country_name, country_code) values ('Poland', 'PL');
insert into geo(country_name, country_code) values ('Austria', 'AT');
insert into geo(country_name, country_code) values ('Hungary', 'HU');
insert into geo(country_name, country_code) values ('Moldova', 'MD');
insert into geo(country_name, country_code) values ('Romania', 'RO');
insert into geo(country_name, country_code) values ('Lithuania', 'LT');
insert into geo(country_name, country_code) values ('Latvia', 'LV');
insert into geo(country_name, country_code) values ('Estonia', 'EE');
insert into geo(country_name, country_code) values ('Germany', 'DE');
insert into geo(country_name, country_code) values ('Bulgaria', 'BG');
insert into geo(country_name, country_code) values ('Greece', 'GR');
insert into geo(country_name, country_code) values ('Turkey', 'TR');
insert into geo(country_name, country_code) values ('Albania', 'AL');
insert into geo(country_name, country_code) values ('Croatia', 'HR');
insert into geo(country_name, country_code) values ('Switzerland', 'CH');
insert into geo(country_name, country_code) values ('Luxembourg', 'LU');
insert into geo(country_name, country_code) values ('Belgium', 'BE');
insert into geo(country_name, country_code) values ('Netherlands', 'NL');
insert into geo(country_name, country_code) values ('Portugal', 'PT');
insert into geo(country_name, country_code) values ('Spain', 'ES');
insert into geo(country_name, country_code) values ('Ireland', 'IE');
insert into geo(country_name, country_code) values ('New Caledonia', 'NC');
insert into geo(country_name, country_code) values ('New Zealand', 'NZ');
insert into geo(country_name, country_code) values ('Australia', 'AU');
insert into geo(country_name, country_code) values ('Sri Lanka', 'LK');
insert into geo(country_name, country_code) values ('China', 'CN');
insert into geo(country_name, country_code) values ('Taiwan', 'TW');
insert into geo(country_name, country_code) values ('Italy', 'IT');
insert into geo(country_name, country_code) values ('Denmark', 'DK');
insert into geo(country_name, country_code) values ('United Kingdom', 'GB');
insert into geo(country_name, country_code) values ('Iceland', 'IS');
insert into geo(country_name, country_code) values ('Azerbaijan', 'AZ');
insert into geo(country_name, country_code) values ('Georgia', 'GE');
insert into geo(country_name, country_code) values ('Philippines', 'PH');
insert into geo(country_name, country_code) values ('Malaysia', 'MY');
insert into geo(country_name, country_code) values ('Brunei Darussalam', 'BN');
insert into geo(country_name, country_code) values ('Slovenia', 'SI');
insert into geo(country_name, country_code) values ('Finland', 'FI');
insert into geo(country_name, country_code) values ('Slovakia', 'SK');
insert into geo(country_name, country_code) values ('Czech Republic', 'CZ');
insert into geo(country_name, country_code) values ('Eritrea', 'ER');
insert into geo(country_name, country_code) values ('Japan', 'JP');
insert into geo(country_name, country_code) values ('Paraguay', 'PY');
insert into geo(country_name, country_code) values ('Yemen', 'YE');
insert into geo(country_name, country_code) values ('Saudi Arabia', 'SA');
insert into geo(country_name, country_code) values ('Cyprus', 'CY');
insert into geo(country_name, country_code) values ('Morocco', 'MA');
insert into geo(country_name, country_code) values ('Egypt', 'EG');
insert into geo(country_name, country_code) values ('Libya', 'LY');
insert into geo(country_name, country_code) values ('Ethiopia', 'ET');
insert into geo(country_name, country_code) values ('Djibouti', 'DJ');
insert into geo(country_name, country_code) values ('Uganda', 'UG');
insert into geo(country_name, country_code) values ('Rwanda', 'RW');
insert into geo(country_name, country_code) values ('Bosnia and Herzegovina', 'BA');
insert into geo(country_name, country_code) values ('Macedonia', 'MK');
insert into geo(country_name, country_code) values ('Trinidad and Tobago', 'TT');
insert into geo(country_name, country_code) values ('South Sudan', 'SS');

